In [1]:
import numpy as np
import random
import pdb

In [2]:
board = "|{0}---{1}---{2}|\n|:   :   :|\n|{3}---{4}---{5}|\n|:   :   :|\n|{6}---{7}---{8}|"

In [3]:
def tie(state):
    if 0 not in state and not win(state,1) and not win(state,2): 
        return True
    else: return False
    
def win(state, token):
    if token == state[0] == state[1] == state[2]: return True
    elif token == state[3] == state[4] == state[5]: return True
    elif token == state[6] == state[7] == state[8]: return True
    elif token == state[0] == state[3] == state[6]: return True
    elif token == state[1] == state[4] == state[7]: return True
    elif token == state[2] == state[5] == state[8]: return True
    elif token == state[0] == state[4] == state[8]: return True
    elif token == state[6] == state[4] == state[2]: return True
    else: return False

In [4]:
class Human:
    def getType(self):
        return "Human"

    def playpart1(self, state):
        move = int(input("Your move: "))
        if move >0 and move < 10:
            return move-1
        else:
            raise ValueError("Entry must be a number between 1 and 9")
            
    def playpart2(self, state):
        piece = int(input("Piece to move: "))
        place = int(input("To: "))
        piece -= 1
        place -= 1
        return piece, place

In [5]:
def numX(state):
    number_of_X = 0
    for i in state:
        if i == 'X': number_of_X += 1
    return number_of_X

def numO(state):
    number_of_O = 0
    for i in state:
        if i == 'O': number_of_O += 1
    return number_of_O

# This function plays the game of 3 men's morris
def playMensMorris(player1, player2):
    numboard = [0 for j in range(9)] # Version of the board with numbers
    XOboard = [' ' for i in range(9)] # Version of the board with X's and O's
    print (board.format(*XOboard), '\n')
    
    # Part 1... players place their pieces
    while (numO(XOboard) < 3 or numX(XOboard) < 3):
        player1_move = player1.playpart1(numboard)
        numboard[player1_move], XOboard[player1_move] = 1, 'X'
        print (board.format(*XOboard), '\n')
            
        if win(XOboard, 'X'): 
            player1_type = player1.getType()
            print("%s wins!" % player1_type)
            break
            
        player2_move = player2.playpart1(numboard)
        numboard[player2_move], XOboard[player2_move] = 2, 'O'
        print (board.format(*XOboard), '\n')
            
        if win(XOboard, 'O'):
            player2_type = player2.getType()
            print ("%s wins!" % player2_type)
            break
    # Part 2...
    while (True):
        # PLAYER 1 TURN
        old_position, new_position = player1.playpart2(numboard)
        # set new position to be what is at old position
        numboard[new_position] = numboard[old_position]
        XOboard[new_position] = XOboard[old_position]
        
        # remove whatever was at the old position
        numboard[old_position], XOboard[old_position] = ' ', ' '
        print(board.format(*XOboard), '\n')
        
        if (win(XOboard, 'X')):
            player1_type = player1.getType()
            print("%s wins!" % player1_type)
            break
        
        # PLAYER 2 TURN
        old_position, new_position = player2.playpart2(numboard)
        # set new position to be what is at old position
        numboard[new_position] = numboard[old_position]
        XOboard[new_position] = XOboard[old_position]
        
        # remove whatever was at the old position
        numboard[old_position], XOboard[old_position] = ' ', ' '
        print(board.format(*XOboard), '\n')
        
        if (win(XOboard, 'O')):
            player1_type = player2.getType()
            print("%s wins!" % player1_type)
            break

In [6]:
class Random: # Random player
    def __init__(self):
        self.moves = []
    
    # Called by playpart1()
    # Returns a random legal move in the state given
    def legalRand(self, state):
        possible = []
        for i in range(len(state)):
            if state[i] == 0:
                possible.append(i)
        return random.choice(possible)
    
    # Called by playpart2()
    # Gets open positions in state relative to the given row and column and
    # adds them to self.moves
    def get_moves(self, state, row, column):
        if (column + 1 < 3 and state[row][column + 1] == 0):
            self.moves.append((row, column+1))
        if (column - 1 >= 0 and state[row][column - 1] == 0):
            self.moves.append((row,column-1))
        if (row + 1 < 3 and state[row+1][column] == 0):
            self.moves.append((row+1, column))
        if (row - 1 >= 0 and state[row-1][column] == 0):
            self.moves.append((row-1, column))
        return
    
    def convert_coordinate(self, coordinate):
        if (coordinate == (0,0)): return 0
        elif (coordinate == (0,1)): return 1
        elif (coordinate == (0,2)): return 2
        elif (coordinate == (1,0)): return 3
        elif (coordinate == (1,1)): return 4
        elif (coordinate == (1,2)): return 5
        elif (coordinate == (2,0)): return 6
        elif (coordinate == (2,1)): return 7
        elif (coordinate == (2,2)): return 8
        
    def playpart1(self, state):
        return self.legalRand(state)
    
    def playpart2(self, state):
        del self.moves[:]
        move_tuples = []
        state = np.array(state).reshape((3,3)) # Transform into 3 x 3 array
        
        for row in range(3):
            for column in range(3):
                if state[row][column] == 2:
                    self.get_moves(state, row, column)
                    print("self.moves: ", self.moves)
                    for x in self.moves:
                        move_tuples.append(((row, column), x))
        print(move_tuples)
        move = random.choice(move_tuples)
        return self.convert_coordinate(move[0]), self.convert_coordinate(move[1])
    
    def getType(self):
        return "Random"

In [7]:
RR = Random()
RR.convert_coordinate((0,0))

0

In [8]:
R = Random()
state = [1,1,2,2,0,1,2,0,0]
print(np.array(state).reshape(3,3))
R.playpart2(state)

[[1 1 2]
 [2 0 1]
 [2 0 0]]
self.moves:  []
self.moves:  [(1, 1)]
self.moves:  [(1, 1), (2, 1)]
[((1, 0), (1, 1)), ((2, 0), (1, 1)), ((2, 0), (2, 1))]


(3, 4)

In [153]:
class QTable: # Q table player
    def __init__(self):
        self.Q = {} # To store the Q-values
        
    def get_moves(self, state, index):
        if (index < 0 or index > 8): return False
        if (state[index] == ' '): return True
    
    def random_move(self, state):
        if state.count(1) == 3 and state.count(2) == 3:
            for i in range(len(state)):
                if state[i] == 'X':
                    del self.moves[:]
                    self.get_moves(i)
            
    def epsilon_greedy(self, epsilon, state):
        if random.random() < epsilon:
            return
        
    def learn(self, games = 10, lrate = 1, df = .5, epsilon = .1):
        for game in range(games):
            # Begin each game with an empty board
            board_state = [0,0,0,0,0,0,0,0,0]
        return

In [154]:
player1 = Human()
player2 = Random()
playMensMorris(player1, player2)

| --- --- |
|:   :   :|
| --- --- |
|:   :   :|
| --- --- | 

Your move: 1
|X--- --- |
|:   :   :|
| --- --- |
|:   :   :|
| --- --- | 

|X--- --- |
|:   :   :|
| --- --- |
|:   :   :|
| ---O--- | 

Your move: 2
|X---X--- |
|:   :   :|
| --- --- |
|:   :   :|
| ---O--- | 

|X---X--- |
|:   :   :|
| ---O--- |
|:   :   :|
| ---O--- | 

Your move: 4
|X---X--- |
|:   :   :|
|X---O--- |
|:   :   :|
| ---O--- | 

|X---X---O|
|:   :   :|
|X---O--- |
|:   :   :|
| ---O--- | 

Piece to move: 4
To: 7
|X---X---O|
|:   :   :|
| ---O--- |
|:   :   :|
|X---O--- | 

[]


IndexError: Cannot choose from an empty sequence